//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrm.DBModels
{
    using EOrm.Attributes;
    using EOrm.Interfaces;
    using System;
    using System.Collections.Generic;

    public partial class Contact : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
        }
    
        [PrimaryKey]
        [ColumnProperty]
        public int ContactId { get; set; }
        [ColumnProperty]
        public string FirstName { get; set; }
        [ColumnProperty]
        public string LastName { get; set; }
        [ColumnProperty]
        public string CellPhone { get; set; }
        public ICollection<Cargo> CustomerCargo { get; set; }
        public ICollection<Cargo> RecipientCargo { get; set; }


        public int Id => ContactId;

        public string GetCreateCommand()
        {
            return $"INSERT INTO Contact(FirstName,LastName,CellPhone) VALUES ('{FirstName}', '{LastName}', '{CellPhone}');";
        }

        public string GetDeleteCommand()
        {
            return $"DELETE FROM Contact WHERE ContactId = {ContactId};";
        }

        public string GetUpdateCommand()
        {
            return $"UPDATE Contact SET FirstName='{FirstName}',LastName='{LastName}',CellPhone='{CellPhone}' WHERE ContactId={ContactId};";
        }
    }
}
