//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrm.DBModels
{
    using EOrm.Attributes;
    using EOrm.Interfaces;
    using System;
    using System.Collections.Generic;
    
    public partial class Route : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
        }

        [PrimaryKey]
        [ColumnProperty]
        public int RouteId { get; set; }
        [ColumnProperty]
        public string Name { get; set; }
        [ColumnProperty]
        public decimal Distance { get; set; }
        [ColumnProperty]
        public int WharehouseStart { get; set; }
        [ColumnProperty]
        public int WharehouseEnd { get; set; }
        public virtual Wharehouse StartPoint { get; set; }
        public virtual Wharehouse EndPoint { get; set; }

        public int Id => RouteId;

        public string GetCreateCommand()
        {
            return $"INSERT INTO Route(Name,Distance,WharehouseStart,WharehouseEnd) VALUES ('{Name}', {Distance}, {WharehouseStart}, {WharehouseEnd});";
        }

        public string GetDeleteCommand()
        {
            return $"DELETE FROM Route WHERE RouteId = {RouteId}";
        }

        public string GetUpdateCommand()
        {
            return $"UPDATE Route SET Name='{Name}',Distance={Distance},WharehouseStart={WharehouseStart},WharehouseEnd={WharehouseEnd} WHERE RouteId={RouteId};";
        }
    }
}
