//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrm.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int ShipmentId { get; set; }
        public int TruckId { get; set; }
        public int DriverId { get; set; }
        public int CargoId { get; set; }
        public int RouteId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Route Route { get; set; }
        public virtual Truck Truck { get; set; }
    }
}
