//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOrm.DBModels
{
    using EOrm.Attributes;
    using EOrm.Interfaces;
    using System;
    using System.Collections.Generic;

    public partial class Wharehouse : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wharehouse()
        {
        }
    
        [PrimaryKey]
        [ColumnProperty]
        public int WharehouseId { get; set; }
        [ColumnProperty]
        public string City { get; set; }
        [ColumnProperty]
        public string State { get; set; }

        public int Id => WharehouseId;

        public string GetCreateCommand()
        {
            return $"INSERT INTO Wharehouse(City,State) VALUES ('{City}', '{State}');";
        }

        public string GetDeleteCommand()
        {
            return $"DELETE FROM Wharehouse WHERE WharehouseId = {WharehouseId}";
        }

        public string GetUpdateCommand()
        {
            return $"UPDATE Wharehouse SET City='{City}',State='{State}' WHERE WharehouseId={WharehouseId};";
        }
    }
}
